### PR TITLE
implement fix_timestamps command

### PR DESCRIPTION
**Pull request by petrjasek**
it will set `versioncreated` to `extra.original_published_at` value

SDESK-5429

### CODE REVIEW

**Comment by petrjasek** [comment]
@takeit just not sure about 1 thing - do you set this `extra.original_published_at` only for ingested items?

**Comment by takeit** [comment]
@petrjasek yes, it's only set for the ingested items

**Comment by takeit** [comment]
@petrjasek is it ready to be merged?

**Comment by petrjasek** [comment]
yep, you can run it via `manage.py fix_timestamps`

**Comment by petrjasek** [comment]
you can set a limit via `-l` to test it on a few items first, without that it should fix all items with that metadata set

**Comment by takeit** [comment]
Perfect!

**Comment by SrdjanKaralic** [comment]
@petrjasek @takeit **extra.original_published_at** should be shown in both **ingested** and **published** items

**Pull request merged**
